name: Metrics
on:
  # 毎日0時に自動更新（UTC）
  schedule: [{cron: "0 0 * * *"}]
  # 手動でもトリガー可能
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore(metrics): update metrics"
          base: "" # 言語グラフだけに絞るならこれ
          plugin_languages: yes
          plugin_languages_details: percentage # %を表示
          plugin_languages_colors: github
          plugin_languages_threshold: 0% # 全言語出したいなら0%
